// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7m7y5Ko5oFdUmWoZsJxiIweMiaAMxdk',
    appId: '1:32669995964:web:61a8413f6fa23a433a91b9',
    messagingSenderId: '32669995964',
    projectId: 'mffp-d3689',
    authDomain: 'mffp-d3689.firebaseapp.com',
    databaseURL: 'https://mffp-d3689.firebaseio.com',
    storageBucket: 'mffp-d3689.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbT2m5rCRa1pv8j1qKWmUPkCJvAVyxJWU',
    appId: '1:32669995964:android:10f4c658012dd3833a91b9',
    messagingSenderId: '32669995964',
    projectId: 'mffp-d3689',
    databaseURL: 'https://mffp-d3689.firebaseio.com',
    storageBucket: 'mffp-d3689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiudezBrmdzmRZnjSPZyEFZm3PghmYrw0',
    appId: '1:32669995964:ios:1a5dd0adc3bf19a63a91b9',
    messagingSenderId: '32669995964',
    projectId: 'mffp-d3689',
    databaseURL: 'https://mffp-d3689.firebaseio.com',
    storageBucket: 'mffp-d3689.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiudezBrmdzmRZnjSPZyEFZm3PghmYrw0',
    appId: '1:32669995964:ios:1a5dd0adc3bf19a63a91b9',
    messagingSenderId: '32669995964',
    projectId: 'mffp-d3689',
    databaseURL: 'https://mffp-d3689.firebaseio.com',
    storageBucket: 'mffp-d3689.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ7m7y5Ko5oFdUmWoZsJxiIweMiaAMxdk',
    appId: '1:32669995964:web:baca69dd6b23f6863a91b9',
    messagingSenderId: '32669995964',
    projectId: 'mffp-d3689',
    authDomain: 'mffp-d3689.firebaseapp.com',
    databaseURL: 'https://mffp-d3689.firebaseio.com',
    storageBucket: 'mffp-d3689.firebasestorage.app',
  );
}
